- name: Create the ELB only listening over port 80
  ec2_elb_lb:
    name: "{{ ELBNAME }}"
    state: present
    region: us-west-2
    subnets:
      - subnet-0799483d066d3f31e
      - subnet-0eb35a0abae60f0a2
    security_group_ids:
      - sg-07d62e2a493f6f870
      - sg-04d341b663dd74c64
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
  register: elb

- name: Create EC2 instances
  ec2:
    key_name: Jenkins-EC2
    instance_type: t2.nano
    image: ami-003634241a8fcdec0
    user_data: "{{ USERDATA }}"
    region: us-west-2
    vpc_id: vpc-08f5ae1a14111bdc5
    group_id:
      - sg-07d62e2a493f6f870
      - sg-04d341b663dd74c64
    wait: yes
    instance_tags:
      Name: web_server
      application: "{{ application }}"
    exact_count: 2
    count_tag:
      application: "{{ application }}"
  register: ec2_instances

- name: Wait for servers to come online
  wait_for:
    host: "{{ item.public_ip }}"
    port: 80
    timeout: 180
  with_items: "{{ ec2_instances.tagged_instances }}"
  ignore_errors: True

- name: Add each EC2 instance to the ELB
  ec2_elb:
    state: present
    ec2_elbs: "{{ ELBNAME }}"
    region: "{{ item.region }}"
    instance_id: "{{ item.id }}"
  with_items: "{{ ec2_instances.tagged_instances }}"
