- name: change route53
  route53:
    state: present
    zone: test.com
    record: www.test.com
    failover: PRIMARY
    type: CNAME
    ttl: 30
    identifier: server1
    private_zone: yes
    overwrite: yes
    value: "{{ NEW_ALIAS }}"
    wait: yes
    health_check: " 13a43f23-61b1-4bf0-99d8-6466486a54b5"
